detection:
   display_mode: True
   record_mode: True
   
   display_masks: True
   display_bboxes: True
   display_scores: True
   
   show_s: True
   show_p: True
   show_w: True
   show_output: True
   show_region: True
   show_time: False
   
   modal_custom: True
   modal_coco: True
   
   target_fps_seucar: 5
   target_fps_test: 15
   
   region_l1: 7
   region_l2: 3
   region_l3: 3
   region_l4: 3
   region_l5: 2
   
   max_width: 0.5
   coordinate_offset_x: 0
   coordinate_offset_y: 0
   
   sub_topic_image: /image_rectified
   pub_topic_areasinfo: /sweeper/area_info
   pub_topic_objects: /sweeper/obstacles
   pub_topic_envinfo: /sweeper/env_info
